const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{vida: 0},
	{posxinicial: 0},
	{posyinicial: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{charmander: 0},
	{Sólido: 0},
	{bloco1: 0},
	{bloco2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Senóide: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{bloco3: 0},
	{bloco4: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{bloco5: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite32: 0},
	{Sprite53: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{plataformafase2: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{Sprite70: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{Sprite75: 0},
	{Sprite76: 0},
	{Sprite78: 0},
	{Sprite79: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{Sprite82: 0},
	{Sprite83: 0},
	{Sprite84: 0},
	{Sprite86: 0},
	{Sprite87: 0},
	{Sprite88: 0},
	{Sprite89: 0},
	{Sprite90: 0},
	{Sprite91: 0},
	{Sprite92: 0},
	{Sprite93: 0},
	{Sprite8: 0},
	{Sprite77: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{Sprite99: 0},
	{Sprite100: 0},
	{Sprite85: 0},
	{Sprite101: 0},
	{Sprite102: 0},
	{Sprite103: 0},
	{Sprite104: 0},
	{Sprite105: 0},
	{Áudio: 0},
	{Sprite106: 0},
	{Sprite37: 0},
	{Sprite107: 0},
	{Sprite108: 0},
	{Sprite109: 0},
	{Sprite110: 0},
	{Sprite111: 0},
	{Sprite112: 0},
	{Sprite113: 0},
	{Sprite114: 0},
	{Sprite115: 0},
	{Sprite116: 0},
	{Sprite117: 0},
	{Sprite118: 0},
	{Sprite119: 0},
	{Sprite120: 0},
	{Sprite121: 0},
	{Sprite122: 0},
	{Sprite123: 0},
	{Sprite124: 0},
	{Sprite125: 0},
	{Sprite126: 0},
	{Sprite127: 0},
	{Sprite128: 0},
	{Sprite129: 0},
	{Sprite130: 0},
	{Sprite131: 0},
	{Sprite132: 0},
	{Sprite133: 0},
	{Sprite134: 0},
	{Sprite135: 0},
	{Sprite136: 0},
	{Sprite137: 0},
	{Sprite138: 0},
	{Sprite139: 0},
	{Sprite140: 0},
	{Sprite141: 0},
	{Sprite142: 0},
	{Sprite143: 0},
	{Sprite144: 0},
	{Sprite145: 0},
	{Sprite146: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{Sprite149: 0},
	{Sprite150: 0},
	{Sprite152: 0},
	{Sprite153: 0},
	{Sprite154: 0},
	{Sprite155: 0},
	{Sprite156: 0},
	{Sprite157: 0},
	{Sprite158: 0},
	{Sprite159: 0},
	{Sprite160: 0},
	{Sprite161: 0},
	{Sprite162: 0},
	{Sprite163: 0},
	{Sprite164: 0},
	{Sprite165: 0},
	{Sprite166: 0},
	{Sprite167: 0},
	{Sprite168: 0},
	{Sprite174: 0},
	{Sprite175: 0},
	{Sprite176: 0},
	{Sprite178: 0},
	{Sprite179: 0},
	{Sprite180: 0},
	{Sprite181: 0},
	{Sprite182: 0},
	{Sprite183: 0},
	{Sprite184: 0},
	{Sprite185: 0},
	{Sprite186: 0},
	{Sprite188: 0},
	{Sprite189: 0},
	{Sprite190: 0},
	{Sprite191: 0},
	{Sprite192: 0},
	{Sprite193: 0},
	{Sprite194: 0},
	{Sprite195: 0},
	{Sprite196: 0},
	{Sprite197: 0},
	{Sprite198: 0},
	{Sprite199: 0},
	{Sprite200: 0},
	{Sprite201: 0},
	{Sprite202: 0},
	{Sprite203: 0},
	{Sprite204: 0},
	{Sprite205: 0},
	{Sprite206: 0},
	{Sprite207: 0},
	{Sprite208: 0},
	{Sprite209: 0},
	{Sprite210: 0},
	{Sprite211: 0},
	{Sprite212: 0},
	{Sprite213: 0},
	{Sprite214: 0},
	{Sprite215: 0},
	{Sprite216: 0},
	{Sprite217: 0},
	{Sprite218: 0},
	{Sprite219: 0},
	{Sprite220: 0},
	{Sprite221: 0},
	{Sprite222: 0},
	{Sprite223: 0},
	{Sprite224: 0},
	{Sprite225: 0},
	{Sprite226: 0},
	{Sprite227: 0},
	{Sprite228: 0},
	{Sprite229: 0},
	{Sprite230: 0},
	{Sprite231: 0},
	{Sprite232: 0},
	{Sprite234: 0},
	{Sprite235: 0},
	{Sprite236: 0},
	{Sprite237: 0},
	{Âncora: 0},
	{Sprite238: 0},
	{Sprite239: 0},
	{Sprite240: 0},
	{Sprite241: 0},
	{Sprite242: 0},
	{Sprite243: 0},
	{Sprite244: 0},
	{Sprite245: 0},
	{Sprite246: 0},
	{Sprite247: 0},
	{Sprite248: 0},
	{vida2: 0},
	{vida1: 0},
	{Sprite254: 0},
	{Sprite255: 0},
	{Sprite256: 0},
	{Sprite257: 0},
	{Teclado: 0},
	{Sprite233: 0},
	{Sprite258: 0},
	{Sprite259: 0},
	{Sprite260: 0},
	{Mouse: 0},
	{Sprite261: 0},
	{Sprite262: 0},
	{Sprite263: 0},
	{Sprite264: 0},
	{Sprite265: 0},
	{direcao: 0},
	{beedrill: 0},
	{Texto: 0},
	{vida3: 0},
	{gameOver: 0},
	{Sprite267: 0},
	{Sprite268: 0},
	{portal01: 0},
	{Sprite250: 0},
	{Sprite251: 0},
	{Sprite249: 0},
	{portal00: 0},
	{portal0: 0},
	{Sprite269: 0},
	{portal: 0},
	{Sprite151: 0},
	{Sprite169: 0},
	{Sprite170: 0},
	{Sprite171: 0},
	{Sprite172: 0},
	{Sprite173: 0},
	{Sprite177: 0},
	{Sprite187: 0},
	{Sprite266: 0},
	{Sprite270: 0},
	{Sprite271: 0},
	{Sprite272: 0},
	{Sprite273: 0},
	{Sprite274: 0},
	{Sprite275: 0},
	{Sprite276: 0},
	{Sprite277: 0},
	{Sprite278: 0},
	{Sprite279: 0},
	{parede2: 0},
	{parede02: 0},
	{Sprite252: 0},
	{Sprite253: 0},
	{Sprite280: 0},
	{Sprite281: 0},
	{Sprite282: 0},
	{agua: 0},
	{Sprite284: 0},
	{Sprite285: 0},
	{Sprite286: 0},
	{Sprite287: 0},
	{Sprite288: 0},
	{Sprite289: 0},
	{Sprite290: 0},
	{Sprite291: 0},
	{Sprite292: 0},
	{Sprite293: 0},
	{Sprite294: 0},
	{Sprite295: 0},
	{Sprite296: 0},
	{Sprite297: 0},
	{Sprite298: 0},
	{Sprite299: 0},
	{Sprite300: 0},
	{Sprite301: 0},
	{Sprite302: 0},
	{Sprite303: 0},
	{Sprite304: 0},
	{Sprite305: 0},
	{Sprite306: 0},
	{Sprite307: 0},
	{Sprite308: 0},
	{Sprite309: 0},
	{Sprite310: 0},
	{Sprite311: 0},
	{Sprite312: 0},
	{agua2: 0},
	{Sprite313: 0},
	{Sprite283: 0},
	{chama: 0},
	{plataformafase3: 0},
	{Sprite60: 0},
	{Sprite314: 0},
	{Sprite315: 0},
	{Sprite316: 0},
	{Sprite317: 0},
	{jogarnovamente: 0},
	{Sprite318: 0},
	{gameOver2: 0},
	{jogarnovamente2: 0},
	{voltar: 0},
	{Texto2: 0},
	{Sprite319: 0},
	{Sprite320: 0},
	{Sprite321: 0},
	{Sprite322: 0},
	{Texto3: 0},
	{Sprite323: 0},
	{Sprite324: 0},
	{Sprite325: 0},
	{vidas: 0}
];

self.InstanceType = {
	charmander: class extends self.ISpriteInstance {},
	bloco1: class extends self.ISpriteInstance {},
	bloco2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	bloco3: class extends self.ISpriteInstance {},
	bloco4: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	bloco5: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	plataformafase2: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	Sprite112: class extends self.ISpriteInstance {},
	Sprite113: class extends self.ISpriteInstance {},
	Sprite114: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	Sprite116: class extends self.ISpriteInstance {},
	Sprite117: class extends self.ISpriteInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite119: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite121: class extends self.ISpriteInstance {},
	Sprite122: class extends self.ISpriteInstance {},
	Sprite123: class extends self.ISpriteInstance {},
	Sprite124: class extends self.ISpriteInstance {},
	Sprite125: class extends self.ISpriteInstance {},
	Sprite126: class extends self.ISpriteInstance {},
	Sprite127: class extends self.ISpriteInstance {},
	Sprite128: class extends self.ISpriteInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	Sprite131: class extends self.ISpriteInstance {},
	Sprite132: class extends self.ISpriteInstance {},
	Sprite133: class extends self.ISpriteInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Sprite135: class extends self.ISpriteInstance {},
	Sprite136: class extends self.ISpriteInstance {},
	Sprite137: class extends self.ISpriteInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	Sprite140: class extends self.ISpriteInstance {},
	Sprite141: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	Sprite146: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Sprite152: class extends self.ISpriteInstance {},
	Sprite153: class extends self.ISpriteInstance {},
	Sprite154: class extends self.ISpriteInstance {},
	Sprite155: class extends self.ISpriteInstance {},
	Sprite156: class extends self.ISpriteInstance {},
	Sprite157: class extends self.ISpriteInstance {},
	Sprite158: class extends self.ISpriteInstance {},
	Sprite159: class extends self.ISpriteInstance {},
	Sprite160: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	Sprite164: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	Sprite166: class extends self.ISpriteInstance {},
	Sprite167: class extends self.ISpriteInstance {},
	Sprite168: class extends self.ISpriteInstance {},
	Sprite174: class extends self.ISpriteInstance {},
	Sprite175: class extends self.ISpriteInstance {},
	Sprite176: class extends self.ISpriteInstance {},
	Sprite178: class extends self.ISpriteInstance {},
	Sprite179: class extends self.ISpriteInstance {},
	Sprite180: class extends self.ISpriteInstance {},
	Sprite181: class extends self.ISpriteInstance {},
	Sprite182: class extends self.ISpriteInstance {},
	Sprite183: class extends self.ISpriteInstance {},
	Sprite184: class extends self.ISpriteInstance {},
	Sprite185: class extends self.ISpriteInstance {},
	Sprite186: class extends self.ISpriteInstance {},
	Sprite188: class extends self.ISpriteInstance {},
	Sprite189: class extends self.ISpriteInstance {},
	Sprite190: class extends self.ISpriteInstance {},
	Sprite191: class extends self.ISpriteInstance {},
	Sprite192: class extends self.ISpriteInstance {},
	Sprite193: class extends self.ISpriteInstance {},
	Sprite194: class extends self.ISpriteInstance {},
	Sprite195: class extends self.ISpriteInstance {},
	Sprite196: class extends self.ISpriteInstance {},
	Sprite197: class extends self.ISpriteInstance {},
	Sprite198: class extends self.ISpriteInstance {},
	Sprite199: class extends self.ISpriteInstance {},
	Sprite200: class extends self.ISpriteInstance {},
	Sprite201: class extends self.ISpriteInstance {},
	Sprite202: class extends self.ISpriteInstance {},
	Sprite203: class extends self.ISpriteInstance {},
	Sprite204: class extends self.ISpriteInstance {},
	Sprite205: class extends self.ISpriteInstance {},
	Sprite206: class extends self.ISpriteInstance {},
	Sprite207: class extends self.ISpriteInstance {},
	Sprite208: class extends self.ISpriteInstance {},
	Sprite209: class extends self.ISpriteInstance {},
	Sprite210: class extends self.ISpriteInstance {},
	Sprite211: class extends self.ISpriteInstance {},
	Sprite212: class extends self.ISpriteInstance {},
	Sprite213: class extends self.ISpriteInstance {},
	Sprite214: class extends self.ISpriteInstance {},
	Sprite215: class extends self.ISpriteInstance {},
	Sprite216: class extends self.ISpriteInstance {},
	Sprite217: class extends self.ISpriteInstance {},
	Sprite218: class extends self.ISpriteInstance {},
	Sprite219: class extends self.ISpriteInstance {},
	Sprite220: class extends self.ISpriteInstance {},
	Sprite221: class extends self.ISpriteInstance {},
	Sprite222: class extends self.ISpriteInstance {},
	Sprite223: class extends self.ISpriteInstance {},
	Sprite224: class extends self.ISpriteInstance {},
	Sprite225: class extends self.ISpriteInstance {},
	Sprite226: class extends self.ISpriteInstance {},
	Sprite227: class extends self.ISpriteInstance {},
	Sprite228: class extends self.ISpriteInstance {},
	Sprite229: class extends self.ISpriteInstance {},
	Sprite230: class extends self.ISpriteInstance {},
	Sprite231: class extends self.ISpriteInstance {},
	Sprite232: class extends self.ISpriteInstance {},
	Sprite234: class extends self.ISpriteInstance {},
	Sprite235: class extends self.ISpriteInstance {},
	Sprite236: class extends self.ISpriteInstance {},
	Sprite237: class extends self.ISpriteInstance {},
	Sprite238: class extends self.ISpriteInstance {},
	Sprite239: class extends self.ISpriteInstance {},
	Sprite240: class extends self.ISpriteInstance {},
	Sprite241: class extends self.ISpriteInstance {},
	Sprite242: class extends self.ISpriteInstance {},
	Sprite243: class extends self.ISpriteInstance {},
	Sprite244: class extends self.ISpriteInstance {},
	Sprite245: class extends self.ISpriteInstance {},
	Sprite246: class extends self.ISpriteInstance {},
	Sprite247: class extends self.ISpriteInstance {},
	Sprite248: class extends self.ISpriteInstance {},
	vida2: class extends self.ISpriteInstance {},
	vida1: class extends self.ISpriteInstance {},
	Sprite254: class extends self.ISpriteInstance {},
	Sprite255: class extends self.ISpriteInstance {},
	Sprite256: class extends self.ISpriteInstance {},
	Sprite257: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite233: class extends self.ISpriteInstance {},
	Sprite258: class extends self.ISpriteInstance {},
	Sprite259: class extends self.ISpriteInstance {},
	Sprite260: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite261: class extends self.ISpriteInstance {},
	Sprite262: class extends self.ISpriteInstance {},
	Sprite263: class extends self.ISpriteInstance {},
	Sprite264: class extends self.ISpriteInstance {},
	Sprite265: class extends self.ISpriteInstance {},
	beedrill: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	vida3: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	Sprite267: class extends self.ISpriteInstance {},
	Sprite268: class extends self.ISpriteInstance {},
	portal01: class extends self.ISpriteInstance {},
	Sprite250: class extends self.ISpriteInstance {},
	Sprite251: class extends self.ISpriteInstance {},
	Sprite249: class extends self.ISpriteInstance {},
	portal00: class extends self.ISpriteInstance {},
	portal0: class extends self.ISpriteInstance {},
	Sprite269: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	Sprite169: class extends self.ISpriteInstance {},
	Sprite170: class extends self.ISpriteInstance {},
	Sprite171: class extends self.ISpriteInstance {},
	Sprite172: class extends self.ISpriteInstance {},
	Sprite173: class extends self.ISpriteInstance {},
	Sprite177: class extends self.ISpriteInstance {},
	Sprite187: class extends self.ISpriteInstance {},
	Sprite266: class extends self.ISpriteInstance {},
	Sprite270: class extends self.ISpriteInstance {},
	Sprite271: class extends self.ISpriteInstance {},
	Sprite272: class extends self.ISpriteInstance {},
	Sprite273: class extends self.ISpriteInstance {},
	Sprite274: class extends self.ISpriteInstance {},
	Sprite275: class extends self.ISpriteInstance {},
	Sprite276: class extends self.ISpriteInstance {},
	Sprite277: class extends self.ISpriteInstance {},
	Sprite278: class extends self.ISpriteInstance {},
	Sprite279: class extends self.ISpriteInstance {},
	parede2: class extends self.ISpriteInstance {},
	parede02: class extends self.ISpriteInstance {},
	Sprite252: class extends self.ISpriteInstance {},
	Sprite253: class extends self.ISpriteInstance {},
	Sprite280: class extends self.ISpriteInstance {},
	Sprite281: class extends self.ISpriteInstance {},
	Sprite282: class extends self.ISpriteInstance {},
	agua: class extends self.ISpriteInstance {},
	Sprite284: class extends self.ISpriteInstance {},
	Sprite285: class extends self.ISpriteInstance {},
	Sprite286: class extends self.ISpriteInstance {},
	Sprite287: class extends self.ISpriteInstance {},
	Sprite288: class extends self.ISpriteInstance {},
	Sprite289: class extends self.ISpriteInstance {},
	Sprite290: class extends self.ISpriteInstance {},
	Sprite291: class extends self.ISpriteInstance {},
	Sprite292: class extends self.ISpriteInstance {},
	Sprite293: class extends self.ISpriteInstance {},
	Sprite294: class extends self.ISpriteInstance {},
	Sprite295: class extends self.ISpriteInstance {},
	Sprite296: class extends self.ISpriteInstance {},
	Sprite297: class extends self.ISpriteInstance {},
	Sprite298: class extends self.ISpriteInstance {},
	Sprite299: class extends self.ISpriteInstance {},
	Sprite300: class extends self.ISpriteInstance {},
	Sprite301: class extends self.ISpriteInstance {},
	Sprite302: class extends self.ISpriteInstance {},
	Sprite303: class extends self.ISpriteInstance {},
	Sprite304: class extends self.ISpriteInstance {},
	Sprite305: class extends self.ISpriteInstance {},
	Sprite306: class extends self.ISpriteInstance {},
	Sprite307: class extends self.ISpriteInstance {},
	Sprite308: class extends self.ISpriteInstance {},
	Sprite309: class extends self.ISpriteInstance {},
	Sprite310: class extends self.ISpriteInstance {},
	Sprite311: class extends self.ISpriteInstance {},
	Sprite312: class extends self.ISpriteInstance {},
	agua2: class extends self.ISpriteInstance {},
	Sprite313: class extends self.ISpriteInstance {},
	Sprite283: class extends self.ISpriteInstance {},
	chama: class extends self.ISpriteInstance {},
	plataformafase3: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite314: class extends self.ISpriteInstance {},
	Sprite315: class extends self.ISpriteInstance {},
	Sprite316: class extends self.ISpriteInstance {},
	Sprite317: class extends self.ISpriteInstance {},
	jogarnovamente: class extends self.ISpriteInstance {},
	Sprite318: class extends self.ISpriteInstance {},
	gameOver2: class extends self.ISpriteInstance {},
	jogarnovamente2: class extends self.ISpriteInstance {},
	voltar: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite319: class extends self.ISpriteInstance {},
	Sprite320: class extends self.ISpriteInstance {},
	Sprite321: class extends self.ISpriteInstance {},
	Sprite322: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite323: class extends self.ISpriteInstance {},
	Sprite324: class extends self.ISpriteInstance {},
	Sprite325: class extends self.ISpriteInstance {}
}